CREATE TABLE CUSTOMER(
  ID VARCHAR(36) PRIMARY KEY,
  FIRST_NAME VARCHAR(64),
  LAST_NAME VARCHAR(64),
  ADDRESS VARCHAR(500),
  DOB DATE,
  AGE NUMBER,
  CREATED_DATE TIMESTAMP,
  UPDATED_DATE TIMESTAMP
);